### ISSUE TITLE
e)c:eyvy

### ISSUE THREAD

**Issue by WaffleLapkin** [WaffleLapkin/teloxidebottest#1]

**Comment by WaffleLapkin** [comment]
@WaffleLapkin label +question

**Comment by WaffleLapkin** [comment]
@WaffleLapkin label -question

**Comment by TheAwiteb** [comment]
@WaffleLapkin claim

**Comment by WaffleLapkin** [comment]
@TheAwiteb it's @teloxidebot

**Comment by TheAwiteb** [comment]
@teloxidebot claim

**Comment by TheAwiteb** [comment]
Nice

**Comment by TheAwiteb** [comment]
@teloxidebot -r

**Comment by TheAwiteb** [comment]
@teloxidebot release-assignment

**Comment by TheAwiteb** [comment]
@WaffleLapkin If there is anything you want to try I'm here
